project_id: 'abip-1kirFQBF75MfEQ3RbMQHRb-5Qgs4qOsPgbXnTtlFjeTTo-ln8885t0'
project_name: 'ABI IBM Security QRadar'
project_code: '84bee679-c25e-49cd-8172-c727cc4f8fe1'
project_type: 'ABI CloudFormation Project Type'
partner_name: 'IBM'
launch_date: '2023-10-04'
repo_name: 'cfn-abi-ibmsecurity-qradar'
templates_info:
  - template_id: 'abi-1kirFQBF75MfEQ3RbMQHRb-5Qgs4qOsPgbXnTtlFjeTTo-ln88rqsi'
    file_name: 'templates/abi-enable-qradar-integration.yaml'
    count_flag: 'true'
  - template_id: 'abi-1kirFQBF75MfEQ3RbMQHRb-5Qgs4qOsPgbXnTtlFjeTTo-ln88tcpg'
    file_name: 'templates/enable-integrations/enable-cloudtrail-integrations.yaml'
    count_flag: 'false'
  - template_id: 'abi-1kirFQBF75MfEQ3RbMQHRb-5Qgs4qOsPgbXnTtlFjeTTo-ln88rrkg'
    file_name: 'templates/enable-integrations/enable-guardduty-integrations.yaml'
    count_flag: 'false'
  - template_id: 'abi-1kirFQBF75MfEQ3RbMQHRb-5Qgs4qOsPgbXnTtlFjeTTo-ln88rt4b'
    file_name: 'enable-integrations/enable-sqs-s3-integrations.yaml'
    count_flag: 'false'
  - template_id: 'abi-1kirFQBF75MfEQ3RbMQHRb-5Qgs4qOsPgbXnTtlFjeTTo-ln88rscd'
    file_name: 'enable-integrations/setup-iam-role.yaml'
    count_flag: 'false'