project:
  name: cfn-abi-ibmsecurity-qradar
  owner: durgadas@ibm.com
  package_lambda: false
  shorten_stack_name: true
  s3_regional_buckets: false
  regions:
    - us-east-1

tests:
  launch-qradar-main:
    parameters:
      pSRASourceS3BucketName: $[taskcat_autobucket]
      pSRAS3BucketRegion: $[taskcat_current_region]
      pSRAStagingS3KeyPrefix: $[taskcat_project_name]
    regions:
      - us-east-1
    template: templates/abi-enable-qradar-integration.yaml
